apiVersion: v1
kind: Service
metadata:
  name: service-web
  labels:
    app: service-web
spec:
  selector:
    app: service-web
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30080
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-web
  labels:
    app: service-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-web
  template:
    metadata:
      labels:
        app: service-web
    spec:
      containers:
      - name: service-web
        image: t0ndre/web_app_devops:v1
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            memory: 512Mi
            cpu: "0.5"
        volumeMounts:
        - mountPath: /app/database
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: app-volume

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: app-volume
    namespace: default
  hostPath:
    path: "/mnt/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-volume
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi